steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/blanche-asociados-website:$COMMIT_SHA",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/blanche-asociados-website:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "blanche-asociados-website"
      - "--image"
      - "gcr.io/$PROJECT_ID/blanche-asociados-website:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY
  workerPool: projects/$PROJECT_ID/locations/us-central1/workerPools/default

images:
  - "gcr.io/$PROJECT_ID/blanche-asociados-website:$COMMIT_SHA"
